#from nmaas87/docker-openwrt:15.05_x64
FROM scratch
#MAINTAINER nmaas87 - https://github.com/nmaas87

#ADD openwrt-x86-64-rootfs.tar.gz /
ADD openwrt-15.05.1-x86-64-rootfs.tar.gz /

RUN mkdir /var/lock
USER root
#CMD /sbin/init

